In [1]:
import numpy as np

In [2]:
#used for array and matrix manipulation

In [10]:
l=[1,2,3,4,5]

In [11]:
arr=np.array(l) #creating array from list

In [6]:
type(arr)

numpy.ndarray

In [8]:
np.asarray(l)#creating array from list

array([1, 2, 3, 4, 5])

In [39]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [14]:
arr.ndim #gives what is dimension of particular array

1

In [13]:
arr1.ndim

2

In [6]:
mat = np.matrix(l) #matrix have 2 dimensions at any point of time

In [5]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [8]:
np.asanyarray(mat) #as matrix is one of the type of array it will not convert matrix remains as it is.

matrix([[1, 2, 3, 4, 5]])

In [12]:
arr

array([1, 2, 3, 4, 5])

In [18]:
a=arr # creating another reference a pointing to same data

In [14]:
a

array([1, 2, 3, 4, 5])

In [15]:
arr[0] = 100
arr

array([100,   2,   3,   4,   5])

In [16]:
a

array([100,   2,   3,   4,   5])

In [25]:
# here we give reference of data to a. arr pointing to data it is reference by writing a = arr we create reference to same data,
# such copy is called sollow copy.

In [27]:
b = np.copy(arr) #it will create separate memory copy data there and then give refernce to new memory location. Any change in b will not affect arr
# deep copy.

In [20]:
b

array([100,   2,   3,   4,   5])

In [23]:
b[0]=232

In [22]:
arr

array([100,   2,   3,   4,   5])

In [29]:
np.fromfunction(lambda i,j: i==j, (3,3)) #using it can generate new array

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [30]:
np.fromfunction(lambda i,j: i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [31]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [32]:
iterable = (i*i for i in range(5))

np.fromiter(iterable, float)

In [35]:
np.fromstring('23 45 56', sep=' ')

array([23., 45., 56.])

In [36]:
np.fromstring('23,45,56', sep=',')

array([23., 45., 56.])

In [37]:
arr

array([100,   2,   3,   4,   5])

In [40]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
arr.ndim

1

In [42]:
arr1.ndim

2

In [43]:
arr.size

5

In [44]:
arr1.size

6

In [45]:
arr.shape

(5,)

In [46]:
arr1.shape

(2, 3)

In [47]:
arr.dtype

dtype('int64')

In [48]:
arr1.dtype

dtype('int64')