In [1]:
import numpy as np

In [2]:
list(range(5))

[0, 1, 2, 3, 4]

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
#list(range(0.4,10.4)) #range always take integers no fractions

In [10]:
list(np.arange(0.4, 10.4, 0.2)) #arange can consider fractions values also.

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004,
 10.20000000000000

In [12]:
np.linspace(1,5,20) #divides entire scale between 1-5 in 20 divsions equally and generates dataset

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [14]:
np.logspace(1,5,10, base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [20]:
np.zeros(5) #generate any dimension array with all 0's

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [21]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [24]:
arr = np.ones((3,4))

In [26]:
arr+5 #every element inside arr is get added by 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [27]:
np.empty((3,4))

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [30]:
arr1 = np.eye(5) #identity matrix

In [31]:
import pandas as pd

In [32]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [38]:
np.random.rand(2,3) #generates random data for any mean and std deviation

array([[0.61261693, 0.41294342, 0.01204139],
       [0.30892239, 0.21691091, 0.06057302]])

In [37]:
np.random.randn(2,3) #generates data which has mean = 0 and std deviation = 1
#when we require normally distrubuted dataset we usse randn()

array([[ 0.32991238,  0.50854247,  0.28994587],
       [-0.29421135, -0.82800932,  0.02296231]])

In [43]:
arr2 = np.random.randint(1,5,(3,4)) #3 row 4 col and data between 1 to 5


In [45]:
arr2

array([[3, 3, 2, 3],
       [3, 3, 1, 2],
       [4, 3, 4, 3]])

In [44]:
arr2.size

12

In [46]:
arr2.shape

(3, 4)

In [48]:
arr2.reshape(6,2) # we can reshape in multiple of data elements like here element are 12 so we may reshape(6,2), (4,3), (3,4)

array([[3, 3],
       [2, 3],
       [3, 3],
       [1, 2],
       [4, 3],
       [4, 3]])

In [49]:
arr2.reshape(4,3)

array([[3, 3, 2],
       [3, 3, 3],
       [1, 2, 4],
       [3, 4, 3]])

In [51]:
arr2.reshape(2,2,3) # can also reshape in multi dimension

array([[[3, 3, 2],
        [3, 3, 3]],

       [[1, 2, 4],
        [3, 4, 3]]])

In [52]:
arr1 = np.random.randint(1,10, (5,6))

In [53]:
arr1

array([[8, 8, 8, 5, 1, 2],
       [5, 3, 5, 5, 3, 9],
       [9, 3, 8, 8, 9, 7],
       [9, 6, 5, 3, 1, 8],
       [7, 3, 3, 3, 5, 1]])

In [54]:
#filtering data >8
arr1>8

array([[False, False, False, False, False, False],
       [False, False, False, False, False,  True],
       [ True, False, False, False,  True, False],
       [ True, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [55]:
arr1[arr1>8]

array([9, 9, 9, 9])

In [56]:
arr1

array([[8, 8, 8, 5, 1, 2],
       [5, 3, 5, 5, 3, 9],
       [9, 3, 8, 8, 9, 7],
       [9, 6, 5, 3, 1, 8],
       [7, 3, 3, 3, 5, 1]])

In [57]:
# extracting elements at index 0,1 of 0th row

In [59]:
arr1[0, [0,1]]

array([8, 8])

In [61]:
arr1[2:4, [2,3]]

array([[8, 8],
       [5, 3]])

In [64]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [63]:
arr1

array([[2, 1, 1],
       [1, 1, 2],
       [2, 1, 2]])

In [65]:
arr2

array([[1, 1, 1],
       [1, 1, 2],
       [1, 1, 2]])

In [67]:
arr1+arr2 #adding corresponding elements

array([[3, 2, 3],
       [3, 2, 3],
       [2, 3, 3]])

In [68]:
arr1-arr2

array([[ 1,  0,  1],
       [ 1,  0, -1],
       [ 0,  1, -1]])

In [69]:
arr1*arr2 #indexwise multiplication not matrix multiplication

array([[2, 1, 2],
       [2, 1, 2],
       [1, 2, 2]])

In [70]:
#matrix multiplication
arr1@arr2

array([[5, 5, 8],
       [4, 4, 6],
       [4, 4, 7]])

In [71]:
arr1/arr2

array([[2. , 1. , 2. ],
       [2. , 1. , 0.5],
       [1. , 2. , 0.5]])

In [72]:
arr1/0

/tmp/ipykernel_1078/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [73]:
### Numpy - Broadcasting

In [74]:
arr=np.zeros((3,4))

In [75]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [77]:
arr+5 #broadcasting 5 to every element

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [78]:
a = np.array([1,2,3,4])

In [79]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [82]:
b = np.array([[3,4,5]]) #for adding with arr we have to take transpose of b

In [83]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [84]:
b

array([[3, 4, 5]])

In [88]:
arr1 = arr+b.T

In [87]:
b.T

array([[3],
       [4],
       [5]])

In [90]:
np.sqrt(arr1) #for every element it finds sqrt

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [91]:
#also take log10, exponential

In [92]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [93]:
np.exp(arr1)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [94]:
np.min(arr1)

3.0

In [95]:
np.max(arr1)

5.0